import React, { useState, useEffect, useContext } from 'react';
import { MovieContext } from './MovieContext';
import { Form, Button } from 'react-bootstrap';
import { addMovie } from './MovieService';


const MovieForm = ({ onSave, editingMovie }) => {
  const { dispatch } = useContext(MovieContext);
  const [movie, setMovie] = useState({ id: '', name: '', time: '', genres: '', video: '' });

  useEffect(() => {
    if (editingMovie) {
      setMovie(editingMovie);
    }
  }, [editingMovie]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (editingMovie) {
      onSave(movie); // Handle editing existing movie
    } else {
      const newMovie = await addMovie(movie); // Add new movie to the database
      dispatch({ type: 'ADD_MOVIE', payload: newMovie });
    }
    setMovie({ id: '', name: '', time: '', genres: '', video: '' }); // Reset form
  };

  return (
    <Form onSubmit={handleSubmit} className='border-[3px] rounded-lg space-x-5 space-y-3 w-full my-5'>
      <Form.Group className='hidden'>
        {/* ID Field (Optional, as IDs are often generated by the backend) */}
      </Form.Group>
      <Form.Group className='flex flex-col'>
        <Form.Label className='font-bold text-lg'>Name</Form.Label>
        <Form.Control
          type="text"
          className='w-[98%] border border-gray-300 p-1 rounded-lg hover:border-blue-100 hover:border-[2px]'
          value={movie.name}
          onChange={(e) => setMovie({ ...movie, name: e.target.value })}
          required
        />
      </Form.Group>
      <Form.Group className='flex flex-col'>
        <Form.Label className='font-bold text-lg'>Duration (Time)</Form.Label>
        <Form.Control
          type="text"
          className='w-[98%] border border-gray-300 p-1 rounded-lg hover:border-blue-100 hover:border-[2px]'
          value={movie.time}
          onChange={(e) => setMovie({ ...movie, time: e.target.value })}
          required
        />
      </Form.Group>
      <Form.Group className='flex flex-col'>
        <Form.Label className='font-bold text-lg'>Genre</Form.Label>
        <Form.Control
          type="text"
          className='w-[98%] border border-gray-300 p-1 rounded-lg hover:border-blue-100 hover:border-[2px]'
          value={movie.genres}
          onChange={(e) => setMovie({ ...movie, genres: e.target.value })}
          required
        />
      </Form.Group>
      <Form.Group className='flex flex-col'>
        <Form.Label className='font-bold text-lg'>Trailer (Video URL)</Form.Label>
        <Form.Control
          type="text"
          className='w-[98%] border border-gray-300 p-1 rounded-lg hover:border-blue-100 hover:border-[2px]'
          value={movie.video}
          onChange={(e) => setMovie({ ...movie, video: e.target.value })}
          required
        />
      </Form.Group>
      <Button type="submit" style={{ marginBottom: '1rem' }} className='bg-green-500 text-white px-3 py-1 rounded-md'>
        {editingMovie ? 'Save' : 'Add Movie'}
      </Button>
    </Form>
  );
};

export default MovieForm;
